### PR TITLE
Fix alignment detection for one column, mixed named/unnamed

### LINKED ISSUE #984: Superfluous whitespace in named function arguments is not removed
# Actual

``` r
styler::style_text('foo(
  img,
  pkg = "abc",
  color       = "lmn",
  font  = "xyz"
)')
#> foo(
#>   img,
#>   pkg = "abc",
#>   color       = "lmn",
#>   font  = "xyz"
#> )
```

<sup>Created on 2022-08-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

# Expected

```r
#> foo(
#>   img,
#>   pkg = "abc",
#>   color = "lmn",
#>   font = "xyz"
#> )
```

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Closes #984.

### CODE REVIEW

File: R/detect-alignment.R [hunk 1]
```diff
@@ -107,7 +107,9 @@ token_is_on_aligned_line <- function(pd_flat) {
   # over columns.
   n_cols <- map_int(pd_by_line, ~ sum(.x$token == "','"))
   previous_line <- current_col <- 0L
-  start_eval <- if (alignment_col1_all_named(pd_by_line)) {
+  # if all col1 are named or there is at max 1 column,
+  # start at column 1, else start at column 2
+  start_eval <- if (max(n_cols) == 1 || alignment_col1_all_named(pd_by_line)) {
```
Comment (IndrajeetPatil) [inline R/detect-alignment.R:112]:
```suggestion
  start_eval <- if (max(n_cols) == 1L || alignment_col1_all_named(pd_by_line)) {
```

**Review by IndrajeetPatil — APPROVED** [review]
LGTM! Thanks.

Just one minor nit to address.

**Comment by lorenzwalthert** [comment]
right... I think it's time to activate the lintr pre-commit hook so my float subsetting does not start to crumble your conutless changes in that field.
