### PR TITLE
Run some tests sequentially

### LINKED ISSUE #1027: Speed test fail randomly with {testthat} 3e parallel running
See https://github.com/r-lib/styler/pull/1020 and others for example. #978. Can we split the {testthat} runs up in two parts and run all but the speed tests in parallel and then the speed tests afterwards? Problems were introduced in https://github.com/r-lib/styler/pull/978#issuecomment-1221965506.

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Closes #1027.

### CODE REVIEW

File: R/testing.R [hunk 1]
```diff
@@ -377,3 +377,9 @@ test_transformers_drop <- function(transformers) {
     }
   })
 }
+
+
+skip_during_parallel <- function() {
+  is_parallel <- as.logical(as.logical(toupper(Sys.getenv("STYLER_TEST_IS_TRULY_PARALLEL", TRUE))))
```
Comment (IndrajeetPatil) [inline R/testing.R:383]: The outer `as.logical()` is unnecessary?

**Review by IndrajeetPatil — APPROVED** [review]
Elegant solution. Thanks!
